package activos.domain;
// Generated 17/03/2019 06:21:43 PM by Hibernate Tools 4.3.1



/**
 * Activos generated by hbm2java
 */
public class Activos  implements java.io.Serializable {


     private Integer idActivos;
     private Barras barras;
     private Bienes bienes;
     private Categorias categorias;
     private Dependencias dependencias;

    public Activos() {
    }

    public Activos(Barras barras, Bienes bienes, Categorias categorias, Dependencias dependencias) {
       this.barras = barras;
       this.bienes = bienes;
       this.categorias = categorias;
       this.dependencias = dependencias;
    }
   
    public Integer getIdActivos() {
        return this.idActivos;
    }
    
    public void setIdActivos(Integer idActivos) {
        this.idActivos = idActivos;
    }
    public Barras getBarras() {
        return this.barras;
    }
    
    public void setBarras(Barras barras) {
        this.barras = barras;
    }
    public Bienes getBienes() {
        return this.bienes;
    }
    
    public void setBienes(Bienes bienes) {
        this.bienes = bienes;
    }
    public Categorias getCategorias() {
        return this.categorias;
    }
    
    public void setCategorias(Categorias categorias) {
        this.categorias = categorias;
    }
    public Dependencias getDependencias() {
        return this.dependencias;
    }
    
    public void setDependencias(Dependencias dependencias) {
        this.dependencias = dependencias;
    }




}


