package activos.domain;
// Generated 17/03/2019 06:21:43 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Barras generated by hbm2java
 */
public class Barras  implements java.io.Serializable {


     private Integer idBarras;
     private String nombre;

    public Barras() {
    }

	
    public Barras(String nombre) {
        this.nombre = nombre;
    }
    public Integer getIdBarras() {
        return this.idBarras;
    }
    
    public void setIdBarras(Integer idBarras) {
        this.idBarras = idBarras;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

}


