package activos.domain;
// Generated 17/03/2019 06:21:43 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Categorias generated by hbm2java
 */
public class Categorias  implements java.io.Serializable {


     private Integer idCategorias;
     private String nombre;

    public Categorias() {
    }

	
    public Categorias(String nombre) {
        this.nombre = nombre;
    }
   
    public Integer getIdCategorias() {
        return this.idCategorias;
    }
    
    public void setIdCategorias(Integer idCategorias) {
        this.idCategorias = idCategorias;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

}


