package activos.domain;
// Generated 17/03/2019 06:21:43 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Comprobante generated by hbm2java
 */
public class Comprobante  implements java.io.Serializable {


     private Integer idComprobante;
     private Tipos tipos;
     private Date fecha;

    public Comprobante() {
    }

	
    public Comprobante(Tipos tipos, Date fecha) {
        this.tipos = tipos;
        this.fecha = fecha;
    }
   
    public Integer getIdComprobante() {
        return this.idComprobante;
    }
    
    public void setIdComprobante(Integer idComprobante) {
        this.idComprobante = idComprobante;
    }
    public Tipos getTipos() {
        return this.tipos;
    }
    
    public void setTipos(Tipos tipos) {
        this.tipos = tipos;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

}


