package activos.domain;
// Generated 17/03/2019 06:21:43 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Dependencias generated by hbm2java
 */
public class Dependencias  implements java.io.Serializable {


     private Integer idDependencias;
     private Usuarios usuarios;
     private String nombre;

    public Dependencias() {
    }

	
    public Dependencias(Usuarios usuarios, String nombre) {
        this.usuarios = usuarios;
        this.nombre = nombre;
    }
   
    public Integer getIdDependencias() {
        return this.idDependencias;
    }
    
    public void setIdDependencias(Integer idDependencias) {
        this.idDependencias = idDependencias;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
  
}


