package activos.domain;
// Generated 17/03/2019 06:21:43 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Estados generated by hbm2java
 */
public class Estados  implements java.io.Serializable {


     private Integer idEstados;
     private String nombre;

    public Estados() {
    }

    public Estados(String nombre) {
       this.nombre = nombre;
    }
   
    public Integer getIdEstados() {
        return this.idEstados;
    }
    
    public void setIdEstados(Integer idEstados) {
        this.idEstados = idEstados;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
}


