package activos.domain;
// Generated 17/03/2019 06:21:43 PM by Hibernate Tools 4.3.1



/**
 * IntermediacomprobanteId generated by hbm2java
 */
public class IntermediacomprobanteId  implements java.io.Serializable {


     private int comprobanteIdComprobante;
     private int bienesIdBienes;

    public IntermediacomprobanteId() {
    }

    public IntermediacomprobanteId(int comprobanteIdComprobante, int bienesIdBienes) {
       this.comprobanteIdComprobante = comprobanteIdComprobante;
       this.bienesIdBienes = bienesIdBienes;
    }
   
    public int getComprobanteIdComprobante() {
        return this.comprobanteIdComprobante;
    }
    
    public void setComprobanteIdComprobante(int comprobanteIdComprobante) {
        this.comprobanteIdComprobante = comprobanteIdComprobante;
    }
    public int getBienesIdBienes() {
        return this.bienesIdBienes;
    }
    
    public void setBienesIdBienes(int bienesIdBienes) {
        this.bienesIdBienes = bienesIdBienes;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof IntermediacomprobanteId) ) return false;
		 IntermediacomprobanteId castOther = ( IntermediacomprobanteId ) other; 
         
		 return (this.getComprobanteIdComprobante()==castOther.getComprobanteIdComprobante())
 && (this.getBienesIdBienes()==castOther.getBienesIdBienes());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getComprobanteIdComprobante();
         result = 37 * result + this.getBienesIdBienes();
         return result;
   }   


}


