package activos.domain;
// Generated 17/03/2019 06:21:43 PM by Hibernate Tools 4.3.1



/**
 * Intermediacomprobante generated by hbm2java
 */
public class Intermediacomprobante  implements java.io.Serializable {


     private IntermediacomprobanteId id;
     private Bienes bienes;
     private Comprobante comprobante;

    public Intermediacomprobante() {
    }

    public Intermediacomprobante(IntermediacomprobanteId id, Bienes bienes, Comprobante comprobante) {
       this.id = id;
       this.bienes = bienes;
       this.comprobante = comprobante;
    }
   
    public IntermediacomprobanteId getId() {
        return this.id;
    }
    
    public void setId(IntermediacomprobanteId id) {
        this.id = id;
    }
    public Bienes getBienes() {
        return this.bienes;
    }
    
    public void setBienes(Bienes bienes) {
        this.bienes = bienes;
    }
    public Comprobante getComprobante() {
        return this.comprobante;
    }
    
    public void setComprobante(Comprobante comprobante) {
        this.comprobante = comprobante;
    }




}


