package activos.domain;
// Generated 17/03/2019 06:21:43 PM by Hibernate Tools 4.3.1



/**
 * Solicitud generated by hbm2java
 */
public class Solicitud  implements java.io.Serializable {


     private Integer idSolicitud;
     private Comprobante comprobante;
     private Dependencias dependencias;
     private Estados estados;
     private String anotaciones;

    public Solicitud() {
    }

	
    public Solicitud(Comprobante comprobante, Dependencias dependencias, Estados estados) {
        this.comprobante = comprobante;
        this.dependencias = dependencias;
        this.estados = estados;
    }
    public Solicitud(Comprobante comprobante, Dependencias dependencias, Estados estados, String anotaciones) {
       this.comprobante = comprobante;
       this.dependencias = dependencias;
       this.estados = estados;
       this.anotaciones = anotaciones;
    }
   
    public Integer getIdSolicitud() {
        return this.idSolicitud;
    }
    
    public void setIdSolicitud(Integer idSolicitud) {
        this.idSolicitud = idSolicitud;
    }
    public Comprobante getComprobante() {
        return this.comprobante;
    }
    
    public void setComprobante(Comprobante comprobante) {
        this.comprobante = comprobante;
    }
    public Dependencias getDependencias() {
        return this.dependencias;
    }
    
    public void setDependencias(Dependencias dependencias) {
        this.dependencias = dependencias;
    }
    public Estados getEstados() {
        return this.estados;
    }
    
    public void setEstados(Estados estados) {
        this.estados = estados;
    }
    public String getAnotaciones() {
        return this.anotaciones;
    }
    
    public void setAnotaciones(String anotaciones) {
        this.anotaciones = anotaciones;
    }




}


