package activos.domain;
// Generated 17/03/2019 06:21:43 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tipos generated by hbm2java
 */
public class Tipos  implements java.io.Serializable {


     private Integer idTipos;
     private String nombre;

    public Tipos() {
    }

    public Tipos(String nombre) {
       this.nombre = nombre;
    }
   
    public Integer getIdTipos() {
        return this.idTipos;
    }
    
    public void setIdTipos(Integer idTipos) {
        this.idTipos = idTipos;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
   
}


